version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
  # In this simple case we don't need persistance storage but would be needed in a production environment of course
  #     volumes: 
  #       - db:/var/lib/postgresql/data
  # volumes:
  #   db:
  #     driver: local

  api:
    image: hello-world-api
    restart: always
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
    ports:
      - '8080:8080'
